// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCspFhW48kBudrpsTfnooQ-9tmZvsJ1l_Q',
    appId: '1:409146424037:web:6068b7f50b8e46b757320c',
    messagingSenderId: '409146424037',
    projectId: 'pdf1-b85d0',
    authDomain: 'pdf1-b85d0.firebaseapp.com',
    storageBucket: 'pdf1-b85d0.appspot.com',
    measurementId: 'G-2P861F63HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYIu5Ri4_9COnLXPo-stQDP_YYIbpL0Zo',
    appId: '1:409146424037:android:74322d8424a6d5ff57320c',
    messagingSenderId: '409146424037',
    projectId: 'pdf1-b85d0',
    storageBucket: 'pdf1-b85d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbtGkAXN5_BhoozbqNlu9o5NHJPfDW2ak',
    appId: '1:409146424037:ios:5f67c8214862dc4b57320c',
    messagingSenderId: '409146424037',
    projectId: 'pdf1-b85d0',
    storageBucket: 'pdf1-b85d0.appspot.com',
    iosClientId: '409146424037-61ukvrllb105m70tkjob8b7kf16qrs15.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbtGkAXN5_BhoozbqNlu9o5NHJPfDW2ak',
    appId: '1:409146424037:ios:a82fe3e22e752b0f57320c',
    messagingSenderId: '409146424037',
    projectId: 'pdf1-b85d0',
    storageBucket: 'pdf1-b85d0.appspot.com',
    iosClientId: '409146424037-1e6aj14ea66kgs7pat356ucsa7igniac.apps.googleusercontent.com',
    iosBundleId: 'com.example.nfcReader',
  );
}
